In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_hdf('events_data.hdf5','table')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32473067 entries, 0 to 32473066
Data columns (total 10 columns):
event_id        int64
app_id          int64
is_active       bool
device_id       int64
timestamp       datetime64[ns]
longitude       float64
latitude        float64
label_id        object
category        object
labels_count    int64
dtypes: bool(1), datetime64[ns](1), float64(2), int64(4), object(2)
memory usage: 2.4+ GB

In [4]:
df.head(2)

,event_id,app_id,is_active,device_id,timestamp,longitude,latitude,label_id,category,labels_count
0,2,5927333115845830913,True,-6401643145415154744,2016-05-01 00:54:12,103.65,30.97,"[549, 710, 704, 548, 172]","[Property Industry 1.0, Relatives 1, Property ...",5
1,2,-5720078949152207372,False,-6401643145415154744,2016-05-01 00:54:12,103.65,30.97,"[721, 704, 548, 302, 303]","[Personal Effectiveness 1, Property Industry 2...",5

In [5]:
a = df.groupby(['event_id'])['app_id'].agg(['count'])

In [6]:
b = df.groupby(['device_id'])['event_id'].agg(['nunique'])

In [7]:
df[df.device_id==-9221026417907250887].event_id.unique().shape

(42,)

In [8]:
(b>=8).sum()

nunique    32529
dtype: int64

In [9]:
df.event_id.unique().shape

(1488096,)

In [10]:
b.max()

nunique    11267
dtype: int64

In [11]:
c = (df[df.device_id==-9222661944218806987])

In [12]:
c.event_id.unique()

array([ 118332, 1048506, 1787011, 1909145, 2129003, 2163095, 2404661,
       3072680])

In [13]:
c.groupby(['app_id'])['is_active'].agg(['mean','count'])

                          mean  count
app_id
-7326028556762203740  1.000000      3
-1633938282180439957  0.875000      8
-1496780918078400356  1.000000      1
-790408166733700925   0.750000      4
 242515674746466978   1.000000      1
 628020936226491308   0.500000      6
 1000519352029378378  0.200000      5
 4348659952760821294  0.333333      6
 5927333115845830913  0.400000      5
 6278190317900024223  1.000000      6
 8253533661389545512  1.000000      3
 8557198901083791098  1.000000      8
 8693964245073640147  0.750000      8

In [14]:
c[c.app_id==-1496780918078400356]

,event_id,app_id,is_active,device_id,timestamp,longitude,latitude,label_id,category,labels_count
24008960,2404661,-1496780918078400356,True,-9222661944218806987,2016-05-01 00:40:57,0.0,0.0,"[713, 704, 548]","[Services 1, Property Industry 2.0, Industry tag]",3

In [15]:
d = df[df.app_id==4348659952760821294].groupby(['device_id'])['is_active'].agg(['count'])

In [16]:
d.ix[-9215722913042087294]

count    25
Name: -9215722913042087294, dtype: int64

In [17]:
df[df.app_id==4348659952760821294].groupby(['device_id'])['is_active'].mean()

device_id
-9222956879900151005    0.812500
-9222661944218806987    0.333333
-9222399302879214035    0.000000
-9221825537663503111    0.411765
-9221767098072603291    0.833333
-9221079146476055829    0.913043
-9221026417907250887    0.407407
-9220452176650064280    0.000000
-9220329415676028483    0.000000
-9220061629197656378    0.000000
-9218960997324667698    0.166667
-9218823910602782607    0.000000
-9218769147970107256    0.000000
-9218056599942247372    0.666667
-9217515328051764906    0.000000
-9217193238265898015    0.000000
-9215766592714662253    0.000000
-9215722913042087294    0.000000
-9215352913819638805    1.000000
-9214850807520229548    0.000000
-9213722931755358670    0.900000
-9213411371629884254    0.000000
-9212412905070443687    0.880000
-9212215094473853407    1.000000
-9211913362970025570    0.022222
-9211539959417136500    0.000000
-9210896665715593536    0.000000
-9210009798393734484    0.714286
-9209849644716288960    0.893617
-9209307853420372553    0.000000
                          ...
 9211099168815311677    0.384615
 9211574006743366474    0.000000
 9212095331267343196    0.000000
 9212543526610768605    0.000000
 9213189127364136969    0.000000
 9213293114647471451    0.333333
 9213413734487005782    0.000000
 9214077775178562796    0.000000
 9214713584881273123    0.000000
 9214756902997105639    0.444444
 9214973890298048476    0.312500
 9215085115859659343    0.000000
 9215099017641499587    0.000000
 9216703939077805910    0.250000
 9216925254504446539    1.000000
 9218059356897525342    0.000000
 9218283674097315131    0.000000
 9218385100288809344    0.200000
 9218742251459735564    0.333333
 9218834552844225772    0.500000
 9219164468944552013    0.024390
 9219842210460037807    0.416667
 9219937375310355234    0.750000
 9220562120895859549    0.000000
 9220814716773471568    1.000000
 9220914901466458680    0.000000
 9221586026451102237    0.000000
 9222110179000857683    0.250000
 9222355582733155698    0.500000
 9222539910510672930    0.000000
Name: is_active, dtype: float64

In [18]:
df[df.app_id==4348659952760821294].groupby(['device_id'])['is_active'].agg(['count'])

                      count
device_id
-9222956879900151005     32
-9222661944218806987      6
-9222399302879214035      9
-9221825537663503111     17
-9221767098072603291      6
-9221079146476055829     23
-9221026417907250887     27
-9220452176650064280      8
-9220329415676028483     12
-9220061629197656378     22
-9218960997324667698      6
-9218823910602782607     17
-9218769147970107256      5
-9218056599942247372      3
-9217515328051764906      2
-9217193238265898015      2
-9215766592714662253      1
-9215722913042087294     25
-9215352913819638805      1
-9214850807520229548      1
-9213722931755358670     10
-9213411371629884254      4
-9212412905070443687     25
-9212215094473853407      7
-9211913362970025570     45
-9211539959417136500      2
-9210896665715593536     19
-9210009798393734484     21
-9209849644716288960     47
-9209307853420372553      5
...                     ...
 9211099168815311677     26
 9211574006743366474      6
 9212095331267343196      9
 9212543526610768605      2
 9213189127364136969      1
 9213293114647471451      9
 9213413734487005782      9
 9214077775178562796     23
 9214713584881273123     10
 9214756902997105639      9
 9214973890298048476     16
 9215085115859659343     13
 9215099017641499587      1
 9216703939077805910      4
 9216925254504446539     58
 9218059356897525342      1
 9218283674097315131      3
 9218385100288809344      5
 9218742251459735564     18
 9218834552844225772      2
 9219164468944552013     41
 9219842210460037807     12
 9219937375310355234      8
 9220562120895859549     13
 9220814716773471568     11
 9220914901466458680     25
 9221586026451102237     11
 9222110179000857683      4
 9222355582733155698      2
 9222539910510672930      1

[49192 rows x 1 columns]

In [19]:
e = df[df.app_id==4348659952760821294]

In [20]:
e[e.device_id==-9215722913042087294]

,event_id,app_id,is_active,device_id,timestamp,longitude,latitude,label_id,category,labels_count
332034,32478,4348659952760821294,False,-9215722913042087294,2016-05-05 04:03:52,121.39,31.22,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
4503932,448260,4348659952760821294,False,-9215722913042087294,2016-05-04 13:53:18,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
5279271,528512,4348659952760821294,False,-9215722913042087294,2016-05-06 21:35:13,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
6187070,620885,4348659952760821294,False,-9215722913042087294,2016-05-04 05:46:53,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
6965321,698575,4348659952760821294,False,-9215722913042087294,2016-05-04 05:42:17,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
7188668,719871,4348659952760821294,False,-9215722913042087294,2016-05-01 05:07:02,0.00,0.00,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
7758722,780041,4348659952760821294,False,-9215722913042087294,2016-05-07 22:27:26,121.46,31.25,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
9310763,933625,4348659952760821294,False,-9215722913042087294,2016-05-04 17:08:28,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
10277377,1030928,4348659952760821294,False,-9215722913042087294,2016-05-02 07:43:33,0.00,0.00,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
10474551,1049829,4348659952760821294,False,-9215722913042087294,2016-05-06 03:35:34,121.39,31.22,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
10707555,1074097,4348659952760821294,False,-9215722913042087294,2016-05-06 21:29:12,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
12402702,1241934,4348659952760821294,False,-9215722913042087294,2016-05-03 20:59:55,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
15503176,1550831,4348659952760821294,False,-9215722913042087294,2016-05-03 14:49:21,121.47,31.26,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
16628727,1663351,4348659952760821294,False,-9215722913042087294,2016-05-04 06:26:39,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
17344485,1737060,4348659952760821294,False,-9215722913042087294,2016-05-06 22:01:17,0.00,0.00,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
19197455,1922085,4348659952760821294,False,-9215722913042087294,2016-05-04 05:39:52,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
22369351,2240359,4348659952760821294,False,-9215722913042087294,2016-05-03 15:42:58,121.48,31.26,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
23008576,2305473,4348659952760821294,False,-9215722913042087294,2016-05-04 05:36:01,0.00,0.00,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
23957611,2398750,4348659952760821294,False,-9215722913042087294,2016-05-04 13:51:01,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
24093616,2413252,4348659952760821294,False,-9215722913042087294,2016-05-06 03:30:55,121.55,31.20,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
24379763,2443132,4348659952760821294,False,-9215722913042087294,2016-05-01 05:09:05,121.39,31.22,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
24392554,2444152,4348659952760821294,False,-9215722913042087294,2016-05-04 06:23:41,121.46,31.27,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
29160618,2920594,4348659952760821294,False,-9215722913042087294,2016-05-07 19:07:54,121.48,31.17,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
29738443,2977986,4348659952760821294,False,-9215722913042087294,2016-05-01 17:12:52,121.39,31.63,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12
30033542,3007340,4348659952760821294,False,-9215722913042087294,2016-05-07 18:10:58,0.00,0.00,"[548, 549, 405, 730, 756, 759, 773, 780, 786, ...","[Industry tag, Property Industry 1.0, Custom l...",12

In [21]:
df.device_id.unique().shape

(60822,)

In [22]:
f = df.groupby(['app_id','device_id'])['is_active'].agg(['count'])

g = df.groupby(['app_id','device_id'])['is_active'].mean()

i = pd.DataFrame(g)

j = i.unstack('device_id')

h = f.unstack('device_id')

h.fillna(0,inplace=True)

j.fillna(0,inplace=True)

h[h<8]=0

h[h>=8]=1

((h.sum())>0).sum()

j.head()

j.columns = j.columns.droplevel()
h.columns = h.columns.droplevel()

h.sort_index(axis=1,ascending=True,inplace=True)
j.sort_index(axis=1,ascending=True,inplace=True)
h.sort_index(axis=0,ascending=True,inplace=True)
j.sort_index(axis=0,ascending=True,inplace=True)

list(j.columns.values)==list(h.columns.values)

k = csr_matrix(j)
l = csr_matrix(h)
m = k.multiply(l)

n = pd.DataFrame(m.toarray())

n.columns = list(j.columns.values)

n.index = list(j.index.values)

o = csr_matrix(n)

def save_sparse_csr(filename,array):
    np.savez(filename,data = array.data ,indices=array.indices,
             indptr =array.indptr, shape=array.shape )

def load_sparse_csr(filename):
    loader = np.load(filename)
    return csr_matrix((  loader['data'], loader['indices'], loader['indptr']),
                         shape = loader['shape'])
save_sparse_csr('crosstab_device_appid',o)